### ISSUE TITLE
Check mongodb lookup plugin

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/mongodb#17]
##### SUMMARY

There were a few commits to the mongodb.py lookup plugin and tests recently. Check these have been included here.

- Bug Report

##### COMPONENT NAME

mongodb.py

**Comment by rhysmeister** [comment]
PR is actually still open https://github.com/ansible/ansible/pull/46579

**Comment by marcosdiez** [comment]
Hi!

I am the author of that module. I don't know what to do here. I am trying to get my code merged since 2018 and somehow my PR never gets approved.

How should I proceed ?

**Comment by rhysmeister** [comment]
Hello @marcosdiez 

Integration tests are failing with the following...

> TASK [lookup_mongodb : assert we complain properly if pymongo is not there] ****
> fatal: [testhost]: FAILED! => {"msg": "lookup plugin (mongodb) not found"}

I asked an Ansible staffer about this and he said you need to use the new FQ name format. So that would be community.mongodb.mongodb.

Cheers,

Rhys
