### ISSUE TITLE
Test multiple versions of MongoDB

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/mongodb#21]
##### SUMMARY

If we can pass ansible variables into ansible-test we can override the version and run the tests using multiple versions of MongoDB. The last two releases should suffice.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ansible-test / github workflow

**Comment by gundalow** [comment]
One way to do this would be to have separate jobs in GitHub Actions for each version to test, and write something into https://github.com/ansible-collections/mongodb/blob/master/tests/integration/targets/setup_mongodb/defaults/main.yml before invoking ansible-test

**Comment by rhysmeister** [comment]
Thanks for the tip.

**Comment by rhysmeister** [comment]
Implemented here https://github.com/ansible-collections/mongodb/pull/26

**Comment by rhysmeister** [comment]
Merged
