### ISSUE TITLE
Namespace references in galaxy.yml

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/mongodb#3]
##### SUMMARY

Incorrect references to namespace/project? Or is this simply waiting for further setup? Same issue in the community.cassandra namespace https://github.com/ansible-collections/cassandra/blob/master/galaxy.yml

galaxy.yml contains references to community.mongo, i.e. 

homepage: https://github.com/ansible-collections/community.mongo

Should this not be...

homepage: https://github.com/ansible-collections/mongodb?

There are references elsewhere to this namespace.project form. These links 404.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
galaxy.yml

**Comment by gundalow** [comment]
Should be https://github.com/ansible-collections/mongo

Feel free to raise PRs to update that. It's an artifact of the collection generation script.

**Comment by rhysmeister** [comment]
assume you meant https://github.com/ansible-collections/mongodb

Fixed with https://github.com/ansible-collections/mongodb/pull/4
